### ISSUE TITLE
Stuck with RELAY_MAP

### ISSUE THREAD

**Issue by Woutvan** [glogiotatidis/tg-relay#3]
Hello,

I want to test this project but i'm stuck with the RELAY_MAP file. How do I need to call that file? Or do I just insert the source channel/group and the destination channel/group inside the main script like this?

`{114xxxx0349:141xxxx854}`

Thanks for a hint!

**Comment by glogiotatidis** [comment]
Hi!

RELAY_MAP is a configuration variable, not a file. Your configuration file is `.env` that you must create. In there you will add a line to define RELAY_MAP like this
`RELAY_MAP=SOURCE_CHANNEL1:DST_CHANNEL1,DST_CHANNEL2;SOURCE_CHANNEL2:DST_CHANNEL3`

Good luck!
